[WIP] Dynamically updatable RV generator
valorem-labs-inc/valorem-core pull request #187
Opened 2023-01-25 03:47 UTC by Flip-Liquid

2023-01-25 16:16 UTC, 0xAlcibiades requested changes

2023-01-25 16:16 UTC, 0xAlcibiades commented on src/DynamicRandomVariableGenerator.sol
> +contract DynamicRandomVariableGenerator is IDynamicRandomVariableGenerator {
I think we should be using a library here rather than a contract with interfaces.

2023-01-25 16:16 UTC, 0xAlcibiades commented on src/interfaces/IDynamicRandomVariableGenerator.sol
> +    struct Element {
I guess the question here is why this needs to be an element struct with a weight and index rather than just a member of an array that is a weight

2023-01-25 16:16 UTC, 0xAlcibiades commented on src/interfaces/IUniformRandom.sol
> +interface IUniformRandom {
I'm not sure we need an interface for this per se, did you see @neodaoist's PR with the randomness source?

2023-02-25 23:16 UTC, Flip-Liquid commented
Closing in favor of neo's PR

2023-02-25 23:16 UTC, closed without merging